package com.sensars.eurostars.ui.screens.clinician.patients_tab

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowDropDown
import androidx.compose.material3.*
import androidx.compose.material.icons.filled.Close
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import com.sensars.eurostars.ui.design.Aquamarine
import java.time.LocalDate
import java.time.format.DateTimeFormatter

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AddPatientPopup(
    isVisible: Boolean,
    onDismiss: () -> Unit,
    onCreatePatient: (PatientData) -> Unit,
    // Optional: when provided, the popup switches to Edit mode
    initialData: PatientData? = null,
    isLoading: Boolean = false,
    errorMessage: String? = null,
    autoGeneratedPatientId: String? = null
) {
    if (isVisible) {
        val isEditMode = initialData != null
        val patientId = (initialData?.id ?: autoGeneratedPatientId)?.trim().orEmpty()
        val isPatientIdReady = patientId.isNotBlank()
        var weight by remember { mutableStateOf(initialData?.weight ?: "") }
        var age by remember { mutableStateOf(initialData?.age ?: "") }
        var height by remember { mutableStateOf(initialData?.height ?: "") }
        var neuropathicLeg by remember { mutableStateOf(initialData?.neuropathicLeg ?: "") }
        var dateOfLastUlcer by remember { mutableStateOf(initialData?.dateOfLastUlcer ?: "") }
        var ulcerActive by remember { mutableStateOf(initialData?.ulcerActive ?: "") }
        
        // If initialData changes after the dialog is shown (async load), update local fields
        LaunchedEffect(initialData) {
            initialData?.let { data ->
                weight = data.weight
                age = data.age
                height = data.height
                neuropathicLeg = data.neuropathicLeg
                dateOfLastUlcer = data.dateOfLastUlcer
                ulcerActive = data.ulcerActive
            }
        }
        
        // Dropdown states
        var neuropathicLegExpanded by remember { mutableStateOf(false) }
        var ulcerActiveExpanded by remember { mutableStateOf(false) }
        
        // Date picker state
        var showDatePicker by remember { mutableStateOf(false) }
        var selectedDate by remember { mutableStateOf<LocalDate?>(null) }
        
        // Format date from LocalDate to YYYY/MM/DD
        val dateFormatter = DateTimeFormatter.ofPattern("yyyy/MM/dd")
        
        val neuropathicLegOptions = listOf("Right", "Left", "Both")
        val ulcerActiveOptions = listOf("Yes", "No", "Healed", "N/A")
        
        // Validation: check if all fields are filled and numeric
        val isPatientIdNumeric = patientId.isNotBlank() && patientId.all { it.isDigit() }
        val isWeightNumeric = weight.isNotBlank() && weight.all { it.isDigit() }
        val isAgeNumeric = age.isNotBlank() && age.all { it.isDigit() }
        val isHeightNumeric = height.isNotBlank() && height.all { it.isDigit() }
        
        // Date validation: YYYY/MM/DD format or N/A
        val isDateValid = dateOfLastUlcer.isBlank() || 
                         dateOfLastUlcer == "N/A" || 
                         dateOfLastUlcer.matches(Regex("^\\d{4}/\\d{2}/\\d{2}$"))
        
        val isFormValid = isPatientIdNumeric && 
                         isWeightNumeric && 
                         isAgeNumeric && 
                         isHeightNumeric

        Dialog(
            onDismissRequest = onDismiss,
            properties = DialogProperties(
                dismissOnBackPress = true,
                dismissOnClickOutside = true
            )
        ) {
            Card(
                modifier = Modifier
                    .width(600.dp)
                    .fillMaxHeight(0.9f)
                    .padding(16.dp),
                shape = RoundedCornerShape(12.dp),
                colors = CardDefaults.cardColors(containerColor = Color.White),
                elevation = CardDefaults.cardElevation(defaultElevation = 8.dp)
            ) {
                    val scrollState = rememberScrollState()
                    Column(
                        modifier = Modifier
                            .padding(24.dp)
                            .verticalScroll(scrollState)
                    ) {
                        // Header with title and close button
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            // Title only
                            Text(
                                text = if (isEditMode) "Edit patient" else "Create a patient",
                                style = MaterialTheme.typography.headlineSmall.copy(
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 20.sp
                                )
                            )

                            // Close icon button at top-right
                            IconButton(
                                onClick = onDismiss,
                                modifier = Modifier.size(36.dp)
                            ) {
                                Icon(
                                    imageVector = Icons.Filled.Close,
                                    contentDescription = "Close",
                                    tint = Color.Gray
                                )
                            }
                        }

                        Spacer(Modifier.height(24.dp))

                        // Form fields
                        Column {
                            Text(
                                text = "Patient Clinical Study ID# *",
                                style = MaterialTheme.typography.bodyMedium.copy(
                                    fontWeight = FontWeight.Medium,
                                    fontSize = 14.sp
                                ),
                                color = Color(0xFF2C2C2C)
                            )
                            Spacer(Modifier.height(8.dp))
                            Box(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(48.dp)
                                    .clip(RoundedCornerShape(8.dp))
                                    .background(Color(0xFFF8F9FA))
                                    .border(
                                        1.dp,
                                        Color(0xFFE1E5E9),
                                        RoundedCornerShape(8.dp)
                                    )
                                    .padding(horizontal = 12.dp),
                                contentAlignment = Alignment.CenterStart
                            ) {
                                Text(
                                    text = if (isPatientIdReady) patientId else "Generating next ID...",
                                    color = if (isPatientIdReady) Color(0xFF2C2C2C) else Color(0xFF9AA4A7),
                                    fontSize = 16.sp,
                                    style = MaterialTheme.typography.bodyMedium
                                )
                            }
                            Spacer(Modifier.height(4.dp))
                            if (!isEditMode) {
                                Text(
                                    text = if (isPatientIdReady) "Assigned automatically based on your clinician roster." else "Fetching the next available Patient ID...",
                                    color = Color(0xFF6B7280),
                                    fontSize = 12.sp,
                                    style = MaterialTheme.typography.bodySmall
                                )
                            }
                        }

                        Spacer(Modifier.height(20.dp))

                        // Weight field
                        PatientFormField(
                            label = "Weight *",
                            value = weight,
                            onValueChange = { weight = it },
                            placeholder = "Enter your weight",
                            unit = "kg",
                            isError = weight.isNotBlank() && !weight.all { it.isDigit() }
                        )
                        
                        // Show error message for Weight if not numeric
                        if (weight.isNotBlank() && !weight.all { it.isDigit() }) {
                            Spacer(Modifier.height(4.dp))
                            Text(
                                text = "Weight must contain only numbers",
                                color = Color.Red,
                                fontSize = 12.sp,
                                style = MaterialTheme.typography.bodySmall
                            )
                        }

                        Spacer(Modifier.height(16.dp))

                        // Age field
                        PatientFormField(
                            label = "Age *",
                            value = age,
                            onValueChange = { age = it },
                            placeholder = "Enter your age",
                            isError = age.isNotBlank() && !age.all { it.isDigit() }
                        )
                        
                        // Show error message for Age if not numeric
                        if (age.isNotBlank() && !age.all { it.isDigit() }) {
                            Spacer(Modifier.height(4.dp))
                            Text(
                                text = "Age must contain only numbers",
                                color = Color.Red,
                                fontSize = 12.sp,
                                style = MaterialTheme.typography.bodySmall
                            )
                        }

                        Spacer(Modifier.height(16.dp))

                        // Height field
                        PatientFormField(
                            label = "Height *",
                            value = height,
                            onValueChange = { height = it },
                            placeholder = "Enter your height",
                            unit = "cm",
                            isError = height.isNotBlank() && !height.all { it.isDigit() }
                        )
                        
                        // Show error message for Height if not numeric
                        if (height.isNotBlank() && !height.all { it.isDigit() }) {
                            Spacer(Modifier.height(4.dp))
                            Text(
                                text = "Height must contain only numbers",
                                color = Color.Red,
                                fontSize = 12.sp,
                                style = MaterialTheme.typography.bodySmall
                            )
                        }

                        Spacer(Modifier.height(16.dp))

                        // Neuropathic Leg dropdown
                        Column {
                            Text(
                                text = "Neuropathic Leg",
                                style = MaterialTheme.typography.bodyMedium.copy(
                                    fontWeight = FontWeight.Medium,
                                    fontSize = 14.sp
                                ),
                                color = Color(0xFF2C2C2C)
                            )
                            Spacer(Modifier.height(8.dp))
                            ExposedDropdownMenuBox(
                                expanded = neuropathicLegExpanded,
                                onExpandedChange = { neuropathicLegExpanded = !neuropathicLegExpanded }
                            ) {
                                OutlinedTextField(
                                    value = neuropathicLeg,
                                    onValueChange = {},
                                    readOnly = true,
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .menuAnchor(),
                                    placeholder = { Text("Select option") },
                                    trailingIcon = {
                                        Icon(
                                            Icons.Default.ArrowDropDown,
                                            contentDescription = null,
                                            modifier = Modifier.clickable { neuropathicLegExpanded = !neuropathicLegExpanded }
                                        )
                                    },
                                    colors = OutlinedTextFieldDefaults.colors(
                                        focusedBorderColor = Aquamarine,
                                        unfocusedBorderColor = Color(0xFFE1E5E9)
                                    ),
                                    shape = RoundedCornerShape(8.dp)
                                )
                                ExposedDropdownMenu(
                                    expanded = neuropathicLegExpanded,
                                    onDismissRequest = { neuropathicLegExpanded = false }
                                ) {
                                    neuropathicLegOptions.forEach { option ->
                                        DropdownMenuItem(
                                            text = { Text(option) },
                                            onClick = {
                                                neuropathicLeg = option
                                                neuropathicLegExpanded = false
                                            }
                                        )
                                    }
                                }
                            }
                        }

                        Spacer(Modifier.height(16.dp))

                        // Date of last Ulcer field with N/A option
                        Column {
                            Text(
                                text = "Date of last Ulcer",
                                style = MaterialTheme.typography.bodyMedium.copy(
                                    fontWeight = FontWeight.Medium,
                                    fontSize = 14.sp
                                ),
                                color = Color(0xFF2C2C2C)
                            )
                            Spacer(Modifier.height(8.dp))
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.spacedBy(8.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                // Clickable date field that opens calendar
                                Box(
                                    modifier = Modifier
                                        .weight(1f)
                                        .height(48.dp)
                                        .clip(RoundedCornerShape(8.dp))
                                        .background(Color(0xFFF8F9FA))
                                        .border(
                                            1.dp,
                                            if (dateOfLastUlcer.isNotBlank() && !isDateValid) Color.Red else Color(0xFFE1E5E9),
                                            RoundedCornerShape(8.dp)
                                        )
                                        .clickable { showDatePicker = true }
                                        .padding(horizontal = 12.dp),
                                    contentAlignment = Alignment.CenterStart
                                ) {
                                    Text(
                                        text = if (dateOfLastUlcer.isEmpty()) "YYYY/MM/DD or N/A" else dateOfLastUlcer,
                                        color = if (dateOfLastUlcer.isEmpty()) Color(0xFF9AA4A7) else Color(0xFF2C2C2C),
                                        fontSize = 16.sp,
                                        style = MaterialTheme.typography.bodyMedium
                                    )
                                }
                                TextButton(
                                    onClick = { 
                                        dateOfLastUlcer = if (dateOfLastUlcer == "N/A") "" else "N/A"
                                        selectedDate = null
                                    },
                                    colors = ButtonDefaults.textButtonColors(
                                        contentColor = Aquamarine
                                    )
                                ) {
                                    Text("N/A")
                                }
                            }
                            
                            // Date Picker Dialog
                            if (showDatePicker) {
                                // Calculate today's date
                                val today = LocalDate.now()
                                val todayMillis = today.atStartOfDay(java.time.ZoneId.systemDefault())
                                    .toInstant()
                                    .toEpochMilli()
                                
                                val datePickerState = rememberDatePickerState(
                                    initialSelectedDateMillis = selectedDate?.let {
                                        it.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli()
                                    },
                                    yearRange = IntRange(today.year - 100, today.year),
                                    selectableDates = object : SelectableDates {
                                        override fun isSelectableDate(utcTimeMillis: Long): Boolean {
                                            val selectedDate = java.time.Instant.ofEpochMilli(utcTimeMillis)
                                                .atZone(java.time.ZoneId.systemDefault())
                                                .toLocalDate()
                                            return !selectedDate.isAfter(today)
                                        }

                                        override fun isSelectableYear(year: Int): Boolean {
                                            return year <= today.year
                                        }
                                    }
                                )
                                
                                Dialog(
                                    onDismissRequest = { showDatePicker = false }
                                ) {
                                    Card(
                                        modifier = Modifier.fillMaxWidth(),
                                        shape = RoundedCornerShape(16.dp)
                                    ) {
                                        Column(
                                            modifier = Modifier.padding(16.dp)
                                        ) {
                                            DatePicker(
                                                state = datePickerState
                                            )
                                            Spacer(Modifier.height(8.dp))
                                            Row(
                                                modifier = Modifier.fillMaxWidth(),
                                                horizontalArrangement = Arrangement.End,
                                                verticalAlignment = Alignment.CenterVertically
                                            ) {
                                                TextButton(
                                                    onClick = { showDatePicker = false }
                                                ) {
                                                    Text("Cancel")
                                                }
                                                Spacer(Modifier.width(8.dp))
                                                TextButton(
                                                    onClick = {
                                                        datePickerState.selectedDateMillis?.let { millis ->
                                                            val instant = java.time.Instant.ofEpochMilli(millis)
                                                            val date = LocalDate.ofInstant(instant, java.time.ZoneId.systemDefault())
                                                            selectedDate = date
                                                            dateOfLastUlcer = date.format(dateFormatter)
                                                        }
                                                        showDatePicker = false
                                                    }
                                                ) {
                                                    Text("OK", color = Aquamarine)
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            if (dateOfLastUlcer.isNotBlank() && !isDateValid) {
                                Spacer(Modifier.height(4.dp))
                                Text(
                                    text = "Format: YYYY/MM/DD or N/A",
                                    color = Color.Red,
                                    fontSize = 12.sp,
                                    style = MaterialTheme.typography.bodySmall
                                )
                            }
                        }

                        Spacer(Modifier.height(16.dp))

                        // Ulcer Active dropdown
                        Column {
                            Text(
                                text = "Ulcer active",
                                style = MaterialTheme.typography.bodyMedium.copy(
                                    fontWeight = FontWeight.Medium,
                                    fontSize = 14.sp
                                ),
                                color = Color(0xFF2C2C2C)
                            )
                            Spacer(Modifier.height(8.dp))
                            ExposedDropdownMenuBox(
                                expanded = ulcerActiveExpanded,
                                onExpandedChange = { ulcerActiveExpanded = !ulcerActiveExpanded }
                            ) {
                                OutlinedTextField(
                                    value = ulcerActive,
                                    onValueChange = {},
                                    readOnly = true,
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .menuAnchor(),
                                    placeholder = { Text("Select option") },
                                    trailingIcon = {
                                        Icon(
                                            Icons.Default.ArrowDropDown,
                                            contentDescription = null,
                                            modifier = Modifier.clickable { ulcerActiveExpanded = !ulcerActiveExpanded }
                                        )
                                    },
                                    colors = OutlinedTextFieldDefaults.colors(
                                        focusedBorderColor = Aquamarine,
                                        unfocusedBorderColor = Color(0xFFE1E5E9)
                                    ),
                                    shape = RoundedCornerShape(8.dp)
                                )
                                ExposedDropdownMenu(
                                    expanded = ulcerActiveExpanded,
                                    onDismissRequest = { ulcerActiveExpanded = false }
                                ) {
                                    ulcerActiveOptions.forEach { option ->
                                        DropdownMenuItem(
                                            text = { Text(option) },
                                            onClick = {
                                                ulcerActive = option
                                                ulcerActiveExpanded = false
                                            }
                                        )
                                    }
                                }
                            }
                        }

                        Spacer(Modifier.height(32.dp))

                        // Error message display
                        if (errorMessage != null) {
                            Text(
                                text = errorMessage,
                                color = Color.Red,
                                fontSize = 14.sp,
                                style = MaterialTheme.typography.bodyMedium
                            )
                            Spacer(Modifier.height(16.dp))
                        }

                        // Action buttons
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.spacedBy(12.dp)
                        ) {
                            // Cancel button
                            OutlinedButton(
                                onClick = onDismiss,
                                modifier = Modifier.weight(1f),
                                colors = ButtonDefaults.outlinedButtonColors(
                                    contentColor = Aquamarine
                                ),
                                border = androidx.compose.foundation.BorderStroke(
                                    1.dp,
                                    Aquamarine
                                ),
                                shape = RoundedCornerShape(8.dp)
                            ) {
                                Text(
                                    text = "Cancel",
                                    fontWeight = FontWeight.Medium,
                                    fontSize = 14.sp
                                )
                            }

                            // Create / Save button
                            Button(
                                onClick = {
                                    if (isFormValid && !isLoading) {
                                        onCreatePatient(
                                            PatientData(
                                                id = patientId,
                                                weight = weight,
                                                age = age,
                                                height = height,
                                                neuropathicLeg = neuropathicLeg,
                                                dateOfLastUlcer = dateOfLastUlcer,
                                                ulcerActive = ulcerActive
                                            )
                                        )
                                    }
                                },
                                modifier = Modifier.weight(1f),
                                enabled = isFormValid && !isLoading,
                                colors = ButtonDefaults.buttonColors(
                                    containerColor = if (isFormValid && !isLoading) Aquamarine else Color.Gray,
                                    disabledContainerColor = Color.Gray
                                ),
                                shape = RoundedCornerShape(8.dp)
                            ) {
                                if (isLoading) {
                                    Text(
                                        text = if (isEditMode) "Saving..." else "Creating...",
                                        color = Color.LightGray,
                                        fontWeight = FontWeight.Medium,
                                        fontSize = 14.sp
                                    )
                                } else {
                                    Text(
                                        text = if (isEditMode) "Save changes" else "Create a patient",
                                        color = if (isFormValid) Color.White else Color.LightGray,
                                        fontWeight = FontWeight.Medium,
                                        fontSize = 14.sp
                                    )
                                }
                            }
                        }
                    }
                }
        }
    }
}

@Composable
private fun PatientFormField(
    label: String,
    value: String,
    onValueChange: (String) -> Unit,
    placeholder: String,
    unit: String? = null,
    modifier: Modifier = Modifier,
    isError: Boolean = false
) {
    Column(modifier = modifier) {
        Text(
            text = label,
            style = MaterialTheme.typography.bodyMedium.copy(
                fontWeight = FontWeight.Medium,
                fontSize = 14.sp
            ),
            color = Color(0xFF2C2C2C)
        )
        
        Spacer(Modifier.height(8.dp))
        
        Row(
            verticalAlignment = Alignment.CenterVertically
        ) {
            BasicTextField(
                value = value,
                onValueChange = onValueChange,
                modifier = Modifier.weight(1f),
                singleLine = true,
                textStyle = MaterialTheme.typography.bodyMedium.copy(
                    fontSize = 16.sp,
                    color = Color(0xFF2C2C2C)
                ),
                cursorBrush = SolidColor(Aquamarine),
                keyboardOptions = KeyboardOptions(
                    keyboardType = if (label.contains("Age") || label.contains("Weight") || label.contains("Height") || label.contains("Patient Clinical Study ID"))
                        KeyboardType.Number
                    else 
                        KeyboardType.Text
                ),
                decorationBox = { innerTextField ->
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(48.dp)
                            .clip(RoundedCornerShape(8.dp))
                            .background(Color(0xFFF8F9FA))
                            .border(
                                1.dp,
                                if (isError) Color.Red else Color(0xFFE1E5E9),
                                RoundedCornerShape(8.dp)
                            )
                            .padding(horizontal = 12.dp),
                        contentAlignment = Alignment.CenterStart
                    ) {
                        if (value.isEmpty()) {
                            Text(
                                text = placeholder,
                                color = Color(0xFF9AA4A7),
                                fontSize = 16.sp
                            )
                        }
                        innerTextField()
                    }
                }
            )
            
            if (unit != null) {
                Spacer(Modifier.width(8.dp))
                Box(
                    modifier = Modifier
                        .height(32.dp)
                        .padding(horizontal = 8.dp)
                        .clip(RoundedCornerShape(4.dp))
                        .background(Color(0xFFF0F2F3))
                        .padding(horizontal = 8.dp),
                    contentAlignment = Alignment.Center
                ) {
                    Text(
                        text = unit,
                        fontSize = 12.sp,
                        color = Color(0xFF6B7280),
                        fontWeight = FontWeight.Medium
                    )
                }
            }
        }
    }
}

data class PatientData(
    val id: String,
    val weight: String,
    val age: String,
    val height: String,
    val neuropathicLeg: String = "",
    val dateOfLastUlcer: String = "",
    val ulcerActive: String = ""
)
